import copy
import os

from isaaclab.envs import ViewerCfg
from isaaclab.utils import configclass

import instinctlab.tasks.parkour.mdp as mdp
from instinctlab.assets.unitree_g1 import (
    G1_29DOF_LINKS,
    G1_29DOF_TORSOBASE_POPSICLE_CFG,
    G1_29Dof_TorsoBase_symmetric_augmentation_joint_mapping,
    G1_29Dof_TorsoBase_symmetric_augmentation_joint_reverse_buf,
    beyondmimic_g1_29dof_actuators,
    beyondmimic_g1_29dof_delayed_actuators,
)
from instinctlab.motion_reference import MotionReferenceManagerCfg
from instinctlab.motion_reference.motion_files.terrain_aware_amass_motion import (
    TerrainAwareAmassMotionCfg as AmassMotionCfgBase,
)
from instinctlab.motion_reference.utils import motion_interpolate_bilinear
from instinctlab.sensors import get_link_prim_targets
from instinctlab.tasks.parkour.config.parkour_env_cfg import ROUGH_TERRAINS_CFG, ParkourEnvCfg

__file_dir__ = os.path.dirname(os.path.realpath(__file__))
G1_CFG = copy.deepcopy(G1_29DOF_TORSOBASE_POPSICLE_CFG)
G1_CFG.spawn.merge_fixed_joints = True
G1_CFG.init_state.pos = (0.0, 0.0, 0.9)
G1_with_shoe_CFG = copy.deepcopy(G1_CFG)
G1_with_shoe_CFG.spawn.asset_path = os.path.abspath(
    f"{__file_dir__}/../../urdf/g1_29dof_torsoBase_popsicle_with_shoe.urdf"
)


@configclass
class AmassMotionCfg(AmassMotionCfgBase):
    path = os.path.expanduser("~/Datasets")
    retargetting_func = None
    filtered_motion_selection_filepath = os.path.expanduser("~/Datasets/parkour_motion_amp_curated.yaml")
    motion_start_from_middle_range = [0.0, 0.9]
    motion_start_height_offset = 0.0
    ensure_link_below_zero_ground = False
    buffer_device = "output_device"
    motion_interpolate_func = motion_interpolate_bilinear
    velocity_estimation_method = "frontward"
    # Per-subterrain start-time sampling. Keys must match ROUGH_TERRAINS_CFG.sub_terrains keys;
    # envs on subterrains not listed in either dict fall back to the ratio-based sampling above.
    # A subterrain may appear in only one of the two dicts (config check raises otherwise).
    #
    # Block layout of parkour_motion_stair_flat_spliced_retargetted.npz
    # (generated by scripts/motion_tools/splice_parkour_motion.py, which prints this table):
    #   UP_A      0.0- 24.0  walk -> stairs up (slow ~0.35 m/s) -> walk -> stand
    #   UP_B     24.0- 51.3  walk -> stairs up (fast ~0.6 m/s)  -> walk -> stand
    #   DOWN_A   51.3- 78.0  walk -> stairs down (slow ~0.4 m/s)-> walk -> stand
    #   DOWN_B   78.0- 99.0  walk -> stairs down (fast ~0.7 m/s)-> walk -> stand
    #   STAND    99.0-122.7 | TURN_L 122.7-147.7 | TURN_R 147.7-172.7
    #   WALK    172.7-217.9 (1.0/0.29/0.74 m/s) | WALK_TURN 217.9-249.3
    #
    # Continuous windows for homogeneous segments (any phase is a valid start). Keep
    # end + episode_length_s (20 s) inside the segment so playback never crosses into
    # unrelated content.
    subterrain_time_ranges_s = {
        "perlin_rough":            (84.0, 131.0),  # WALK + WALK_TURN
        "perlin_rough_stand":      (151.0, 156.0),   # STAND
    }
    # Discrete segment heads for segmented skills: each reset picks one candidate uniformly,
    # so every episode plays one complete clip from its beginning. Add more candidates as the
    # concatenated motion file gains stair clips (e.g. different speeds / step heights).
    subterrain_start_times_s = {
        "pyramid_stairs":          [0.0, 21.0],     # UP_A slow / UP_B fast
        # "down_up":               [0.0, 24.0],
        "pyramid_stairs_inv":      [42.0, 63.0],    # DOWN_A slow / DOWN_B fast
        # "up_down":               [51.3, 78.0],
    }


motion_reference_cfg = MotionReferenceManagerCfg(
    prim_path="{ENV_REGEX_NS}/Robot/torso_link",
    robot_model_path=G1_CFG.spawn.asset_path,
    reference_prim_path="/World/envs/env_.*/RobotReference/torso_link",
    symmetric_augmentation_link_mapping=[0, 1, 3, 2, 5, 4, 7, 6, 9, 8, 11, 10, 13, 12],
    symmetric_augmentation_joint_mapping=G1_29Dof_TorsoBase_symmetric_augmentation_joint_mapping,
    symmetric_augmentation_joint_reverse_buf=G1_29Dof_TorsoBase_symmetric_augmentation_joint_reverse_buf,
    frame_interval_s=0.02,
    update_period=0.02,
    num_frames=10,
    motion_buffers={
        "run_walk": AmassMotionCfg(),
    },
    link_of_interests=[
        "pelvis",
        "torso_link",
        "left_shoulder_roll_link",
        "right_shoulder_roll_link",
        "left_elbow_link",
        "right_elbow_link",
        "left_wrist_yaw_link",
        "right_wrist_yaw_link",
        "left_hip_roll_link",
        "right_hip_roll_link",
        "left_knee_link",
        "right_knee_link",
        "left_ankle_roll_link",
        "right_ankle_roll_link",
    ],
    mp_split_method="Even",
)


ROUGH_TERRAINS_CFG_PLAY = copy.deepcopy(ROUGH_TERRAINS_CFG)
for sub_terrain_name, sub_terrain_cfg in ROUGH_TERRAINS_CFG_PLAY.sub_terrains.items():
    sub_terrain_cfg.wall_prob = [0.0, 0.0, 0.0, 0.0]


@configclass
class G1ParkourRoughEnvCfg(ParkourEnvCfg):
    def __post_init__(self):
        # post init of parent
        super().__post_init__()
        # Scene
        self.scene.terrain.terrain_generator = ROUGH_TERRAINS_CFG
        self.scene.robot = G1_CFG.replace(prim_path="{ENV_REGEX_NS}/Robot")
        self.scene.robot.actuators = beyondmimic_g1_29dof_delayed_actuators
        self.scene.camera.mesh_prim_paths.extend(get_link_prim_targets(G1_29DOF_LINKS))
        self.scene.motion_reference = motion_reference_cfg


class ShoeConfigMixin:
    def apply_shoe_config(self):
        self.scene.robot = G1_with_shoe_CFG.replace(prim_path="{ENV_REGEX_NS}/Robot")
        self.scene.leg_volume_points.points_generator.z_min = -0.063
        self.scene.leg_volume_points.points_generator.z_max = -0.023
        self.rewards.rewards.foothold_support.params["sole_offset"] = (0.039, 0.0, -0.058)


@configclass
class G1ParkourRoughEnvCfg_PLAY(G1ParkourRoughEnvCfg):
    def __post_init__(self):
        # post init of parent
        super().__post_init__()
        self.scene.terrain.terrain_generator = ROUGH_TERRAINS_CFG_PLAY
        # make a smaller scene for play
        self.scene.num_envs = 1
        # self.viewer = ViewerCfg(
        #     eye=[4.0, 0.75, 1.0],
        #     lookat=[0.0, 0.75, 0.0],
        #     origin_type="asset_root",
        #     asset_name="robot",
        # )

        self.scene.env_spacing = 2.5
        self.episode_length_s = 10
        self.terminations.root_height = None
        # spawn the robot randomly in the grid (instead of their terrain levels)
        # reduce the number of terrains to save memory
        if self.scene.terrain.terrain_generator is not None:
            self.scene.terrain.terrain_generator.num_rows = 4
            self.scene.terrain.terrain_generator.num_cols = 10

        self.scene.leg_volume_points.debug_vis = True
        self.commands.base_velocity.debug_vis = True
        self.events.physics_material = None
        self.events.reset_robot_joints.params = {
            "position_range": (0.0, 0.0),
            "velocity_range": (0.0, 0.0),
        }


@configclass
class G1ParkourEnvCfg(G1ParkourRoughEnvCfg, ShoeConfigMixin):
    def __post_init__(self):
        super().__post_init__()
        self.apply_shoe_config()


@configclass
class G1ParkourEnvCfg_PLAY(G1ParkourRoughEnvCfg_PLAY, ShoeConfigMixin):
    def __post_init__(self):
        super().__post_init__()
        self.apply_shoe_config()